#!/bin/bash

HL2SDK_DIR=""
ASIO_DIR=""
CRYPTOPP_DIR=""

cmake -DCMAKE_BUILD_TYPE=Release -DHL2SDK-CSGO:PATH=$HL2SDK_DIR -DASIO-SRC:PATH=$ASIO_DIR -DCRYPTOPP-SRC:PATH=$CRYPTOPP_DIR -DEXECUTABLE_OUTPUT_PATH=$PWD/build/Release
make
